repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        language_version: python3.11
      - id: end-of-file-fixer
        language_version: python3.11
      - id: check-yaml
        language_version: python3.11
      - id: debug-statements
        language_version: python3.11
      - id: name-tests-test
        language_version: python3.11
      - id: check-added-large-files
        language_version: python3.11
      - id: check-byte-order-marker
        language_version: python3.11
      - id: requirements-txt-fixer
        language_version: python3.11
      - id: detect-private-key
        language_version: python3.11
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.11.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
